### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by zuloo** [tobast/weenotify#2]
hi,
it should be client.run() instead of client.start() in the main() function.
but asside that its a great script, 

PS: maybe note the password option in the readme, so not everybody has to run it with -h first ^^

**Comment by tobast** [comment]
Hi!

`client.start()` is actually what we really want, see <https://docs.python.org/3/library/threading.html#threading.Thread.start>.

The project is hopefully going to be heavily changed on the coming days, including the configuration file format (we're intending to move to a more generic format, like yaml), so I won't bother documenting the option right now, but I'll try do to better for the next version :)

Thanks for the feedback anyway!
